import { darkTheme, lightTheme } from "@/theme/theme";
import { Container, CssBaseline, ThemeProvider } from "@mui/material";
import type { Metadata } from "next";
import LayoutHeader from "./components/header";
import Main from "./components/main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={darkTheme}>
          <CssBaseline />
          <LayoutHeader />
          <Container component="main" sx={{ py: 4 }}>
            <Main>{children}</Main>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
